name: Mirror to fenworksapp

on:
  push:
    branches:
        - master

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Fetch NA repository
        uses: actions/checkout@v2
        with:
          repository: https://github.com/MirandO98/mirror_test.gitt
          ref: 'main'
          path: 'mirror_test'

      - name: Mirror changes to fenworksapp
        run: |
          git remote add mirror_test https://github.com/MirandO98/mirror_test.git
          git push -f mirror_test ${GITHUB_REF}

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
