name: Mirror Changes

on:
  push:
    branches:
      - master  

jobs:
  mirror_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Network-Automation repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0  

      - name: Configure Git
        run: |
          git config --global user.name "Mirand Osmani"
          git config --global user.email "osmanimirand@gmail.com"

      - name: Mirror changes to mirror_test repository
        env:
          GIT_TOKEN: ${{ secrets.PAT_TOKEN }} 
        run: |
          git clone --bare https://github.com/MirandO98/mirror_test.git
          cd bare-clone
          git push --mirror https://github.com/MirandO98/mirror_test.git
          rm -rf bare-clone

