name: Mirror Changes

on:
  push:
    branches:
      - master
      
  

jobs:
  mirror_changes:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout fenworks repository
        uses: actions/checkout@v2
        with:
          repository: https://github.com/MirandO98/Network-Automation.git
          ref: ${{ github.ref }}
      
      - name: Configure Git
        run: |
          git config --global user.name "Mirand Osmani"
          git config --global user.email "osmanimirand@gmail.com"
      
      - name: Mirror changes to fenworksapp repository 
        run: |
          git remote add mirror_test https://github.com/MirandO98/mirror_test.git
          git push --mirror mirror_test
