name: Mirror Production Branch to Client

on:
  push:
    branches:
      - master

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Git credentials
      run: |
        git config --global user.name "Mirand Osmani"
        git config --global user.email "osmanimirand@gmail.com"
        git config --global credential.helper store
        echo "https://github.com:$GITHUB_TOKEN@github.com" > ~/.git-credentials

    - name: Mirror to Client's Repository
      env:
        SOURCE_REPO: MirandO98/Network-Automation
        TARGET_REPO: krenar-telos/test_mirroring
      run: |
        git clone https://github.com/$SOURCE_REPO source_repo
        cd source_repo
        git remote add client_repo https://github.com/$TARGET_REPO
        git push --mirror client_repo

    - name: Clean up
      run: |
        cd ..
        rm -rf source_repo
